### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by jtcnh**
+ added readme
+ changed wolf armor

### CODE REVIEW

**Comment by jtcnh** [comment]
# Formally Requesting You Accept my PR!
Please accept my PR!

**Comment by foshesss** [comment]
Hmmm

**Comment by golden2402** [comment]
why should i...

**Comment by noahrepublic** [comment]
I like this :)

**Comment by ZenumM** [comment]
OMEGALUL

**Comment by jtcnh** [comment]
nerf boar

**Review by golden2402 — APPROVED** [review]

**Comment by ZenumM** [comment]
Good job, John!

**Pull request merged**
